app: book-citation
service: book-citation-api
org: sogoagain

provider:
  name: aws
  runtime: nodejs12.x
  stage: 'service'
  region: ap-northeast-2
  stackName: book-citation-api
  apiName: book-citation-api
  memorySize: 128
  environment:
    API_KAKAO: ${self:custom.env.api.api_kakao}
    KEY_KAKAO: ${self:custom.env.api.key_kakao}
    FRONT_DOMAIN: ${self:custom.env.api.front_domain}
    MODE: 'service'

functions:
  getBooks:
    name: book-citation-api-getBooks
    handler: src/handler.getBooks
    description: get books by keyword and page
    events:
      - http:
          path: books
          method: get
          cors: true

custom:
  stages:
    - service
  env: ${file(./config/env.json)}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  customDomain:
    domainName: ${self:custom.env.domain.name}
    stage: ${opt:alias,'dev'}
    basePath: 'api'
    certificateName: ${self:custom.env.domain.cert}
    createRoute53Record: true
    certificateArn: ${self:custom.env.domain.certificateArn}
  serverless-offline:
    httpPort: 4000

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-aws-alias
  - serverless-webpack
  - serverless-domain-manager
