app: book-citation
service: book-citation-api
org: sogoagain

provider:
  name: aws
  runtime: nodejs12.x
  stage: 'service'
  region: ap-northeast-2
  stackName: book-citation-api
  apiName: book-citation-api
  environment:
    KEY_KAKAO: ${self:custom.env.api.key_kakao}
    MODE: 'service'

functions:
  getBooks:
    name: book-citation-api-getBooks
    handler: src/api/handler.getBooks
    description: get books by keyword and page
    events:
      - http:
          path: books
          method: get
          cors: true

custom:
  stages:
    - service
  env: ${file(./config/env.json)}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  customDomain:
    domainName: ${self:custom.env.domain.name}
    stage: 'service'
    basePath: api
    certificateName: ${self:custom.env.domain.cert}
    createRoute53Record: true
    securityPolicy: tls_1_2

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-aws-alias
  - serverless-webpack
  - serverless-domain-manager
