app: book-citation
service: book-citation-api

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  stackName: book-citation-api-${self:provider.stage}
  apiName: book-citation-api-${self:provider.stage}
  memorySize: 512
  timeout: 30
  architecture: arm64
  endpointType: REGIONAL

  environment:
    KAKAO_API_KEY: ${env:KAKAO_API_KEY}
    FRONT_DOMAIN: ${env:FRONT_DOMAIN}
    NODE_ENV: ${self:provider.stage}

  httpApi:
    cors:
      allowedOrigins:
        - ${env:FRONT_DOMAIN}
      allowedHeaders:
        - Content-Type
      allowedMethods:
        - GET
        - POST
        - OPTIONS

functions:
  getBooks:
    handler: src/handler.default
    events:
      - httpApi:
          path: /books
          method: get

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: node20
    platform: node
    format: cjs
    mainFields: [main, module]
    exclude:
      - aws-sdk

  serverless-offline:
    httpPort: 4000
    lambdaPort: 3002

useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-offline
